.github/workflows/docker-build.yml

Added docker build job

---

.github/workflows/docker-build.yml
.github/workflows/release.yml
Dockerfile
pom.xml

Added release job

---

.github/workflows/release.yml

Enable release job for main branch

---

pom.xml

Do release

---

.github/workflows/release.yml

Use SSH key

---

.github/workflows/release.yml

Create release branch

---

.github/workflows/release.yml

Fixed PR config

---

.github/workflows/release.yml

Push release branch

---

.github/workflows/release.yml

Fixed (hopefully) release branch

---

.github/workflows/release.yml

Run in batch mode

---

.github/workflows/release.yml

Fix JAVA_HOME

---

.github/workflows/release.yml

Set development version

---

.github/workflows/release.yml

Remove pom backups

---

.github/workflows/release.yml

Create Github release

---

.github/workflows/release.yml

Keep new branch

---

.github/workflows/release.yml

Fixed pull request

---

.github/workflows/release.yml

Use Github CLI for creating PR

---

pom.xml

Merge nic/feat/version_update_to_1.1.0-SNAPSHOT into main

---

.github/workflows/ci.yml
Dockerfile

Be compatible with linux/amd64,linux/arm64,linux/s390x

---

README.md
helm-charts/jitsi-conference-mapper/templates/configmap.yaml
helm-charts/jitsi-conference-mapper/templates/deployment.yaml
helm-charts/jitsi-conference-mapper/values.yaml

fix helmchart

---

.github/workflows/ci.yml

Always push image

---

.github/workflows/ci.yml

Run workflow on version tags

---

pom.xml

Merge nic/feat/version_update_to_1.2.0-SNAPSHOT into main

---

src/main/resources/liquibase/00000000000000_initial_schema.xml

- change initial increment value to meet 7 digits

change initial value to meet 7 digits

---

pom.xml

Merge nic/feat/version_update_to_1.3.0-SNAPSHOT into main
